### ISSUE TITLE
Unable to Compile the project 

### ISSUE THREAD

**Issue by ankushdesai** [p-org/P-Boogie-Translation#12]
I tried compiling the project from VS 2017 developer command-prompt.

Running init.bat fails with many errors (failing to compile both P and Corral)

Also, compiling PBoogieTranslator.sln from VS fails with an error CheckP.dll not found.

Can you please help with how I can compile and run the PBoogieTranslator.

**Comment by ellab123** [comment]
I never tried to compile it in VS2017…

**Comment by ankushdesai** [comment]
Can you please check if it works with VS 2015?
Are you able to do both run init.bat and compile PBoogieTranslator successfully using VS 2015?

**Comment by shazqadeer** [comment]
I have fixed init.bat so that it does not try to compile P.sln.  The relevant projects from the P enlistment are directly included in PBoogieTranslator.sln.  I am now able to compiler the solution with both VS 2015 and VS 2017.
